# SSMR: generate SSM model from trajectory data

In [1]:
import numpy as np
from copy import deepcopy
from os.path import join

In [2]:
%matplotlib qt
import matplotlib.pyplot as plt

In [3]:
%load_ext autoreload
%autoreload 2
import utils as utils
import plot_utils as plot

In [4]:
np.set_printoptions(linewidth=300)

## Settings for SSM model

In [5]:
observables = "delay-embedding" # "pos-vel" # 
N_DELAY = 4 # only relevant if observables is "delay-embedding"
TIP_NODE = 51
N_NODES = 709
INPUT_DIM = 8
DT = 0.01

rDOF = 3
oDOF = 3
SSMDim = 6

SSMOrder = 3
obsDim = 2*oDOF
ROMOrder = 3

## Import and inspect decay data

In [7]:
if observables == "pos-vel":
    output_node = 'all'
elif observables == "delay-embedding":
    output_node = TIP_NODE
t_in = 1
t_out = 4

robot_dir = "../../../soft-robot-control/examples/trunk"
data_dir = "/media/jonas/Backup Plus/jonas_soft_robot_data/trunk_adiabatic/north"
rest_file = join(robot_dir, 'rest_qv.pkl')


decayData_dir =  join(data_dir, "decay") # join(robot_dir, "dataCollection/origin") # 
Data = {}
Data['oData'] = utils.import_pos_data(decayData_dir, rest_file=rest_file, output_node=output_node, t_in=t_in, t_out=t_out)

nTRAJ = len(Data['oData'])
print("nTRAJ:", nTRAJ)

nTRAJ: 40


Mainly required for adiabatic setting: Load info.yaml to get pre-tensioning that was used to obtain the decay data as well as the resulting equilibrium position

In [8]:
import yaml
with open(join(decayData_dir, "info.yaml"), "r") as f:
    info = yaml.safe_load(f)
# if 'qv_eq' in info:
#     qv_eq = np.array(info['qv_eq'])
#     print(f"Loaded offset equilibrium position from info.yaml: {qv_eq}")
# else:
q_eq = np.mean([Data['oData'][i][1][:, -1] for i in range(nTRAJ)], axis=0)
u_eq = np.array(info['pre_tensioning'])
# qv_eq = np.hstack((q_eq, np.zeros_like(q_eq)))
# info['q_eq'] = q_eq.astype(float).tolist()
# print(f"Computed equilbrium position from data and saved to info.yaml: {q_eq}")
# with open(join(decayData_dir, "info.yaml"), "w") as f:
#     yaml.dump(info, f, default_flow_style=True)
print(u_eq)
print(q_eq)

[200   0   0   0 200   0   0   0]
[ 0.54467017 35.57246381 -6.34727727]


Change of coordinates: shift oData to the offset equilibrium position

In [9]:
# if observables == "delay-embedding":
#     rest_position = q_eq[:3]
# elif observables == "pos-vel":
#     rest_position = q_eq[]
for i in range(nTRAJ):
    Data['oData'][i][1] = (Data['oData'][i][1].T - q_eq).T

## Observables

EITHER compute reduced coordinates using delay embedding on the available oData OR use position and velocity of all nodes as observables

In [10]:
if observables == "delay-embedding":
    # observables are position of tip + n_delay delay embeddings of the tip position
    assemble_observables = lambda oData: utils.delayEmbedding(oData, up_to_delay=N_DELAY)
elif observables == "pos-vel":
    # observables is position and velocity of tip node
    def assemble_observables(oData):
        if oData.shape[0] > 6:
            tip_node_slice = np.s_[3*TIP_NODE:3*TIP_NODE+3]
        else:
            tip_node_slice = np.s_[:3]
        return np.vstack((oData[tip_node_slice, :], np.gradient(oData[tip_node_slice, :], DT, axis=1)))

Compute observables

In [11]:
Data['yData'] = deepcopy(Data['oData'])
for i in range(nTRAJ):
    Data['yData'][i][1] = assemble_observables(Data['oData'][i][1])

### Plot observables of interest

In [12]:
outdofs = [0, 1, 2]
plt.close('all')
# plot trajectories in 3D [x, y, z] space
plot.traj_3D(Data,
             xyz_idx=[('yData', outdofs[0]), ('yData', outdofs[1]), ('yData', outdofs[2])],
             xyz_names=[r'$x$ [mm]', r'$y$ [mm]', r'$z$ [mm]'])
# plot evolution of x, y and z in time, separately in 3 subplots
highlight_traj = [] # [14, 16, 18, 31, 35, 44] # []
plot.traj_xyz(Data,
             xyz_idx=[('yData', outdofs[0]), ('yData', outdofs[1]), ('yData', outdofs[2])],
             xyz_names=[r'$x$ [mm]', r'$y$ [mm]', r'$z$ [mm]'],
             highlight_idx=highlight_traj)
if observables == "pos-vel":
    # plot trajectories in 3D [x, x_dot, z] space / NB: x_dot = v_x
    plot.traj_3D(Data,
                xyz_idx=[('yData', outdofs[0]), ('yData', outdofs[0]+oDOF), ('yData', outdofs[2])],
                xyz_names=[r'$x$ [mm]', r'$\dot{x}$ [mm/s]', r'$z$ [mm]'])

Slice trajectories, i.e. remove time before they converge with SSM and cut off the end after complete decay

In [13]:
t_interval = [0.1, 3]
Data['oDataTrunc'] = utils.slice_trajectories(Data['oData'], t_interval)
Data['yDataTrunc'] = utils.slice_trajectories(Data['yData'], t_interval)

## Obtain reduced-order coordinates

### Perform PCA on delay-embedded coordinates to obtain reduced coordinates

In [14]:
if observables == "pos-vel":
    svd_data = 'oDataTrunc'
elif observables == "delay-embedding":
    svd_data = 'yDataTrunc'

Xsnapshots = np.hstack([yDataTrunc[1] for yDataTrunc in Data[svd_data]])
Xsnapshots = Xsnapshots[:, :]

show_modes = 9
Xsnapshots = np.hstack([DataTrunc[1] for DataTrunc in Data[svd_data]])
v, s = utils.sparse_svd(Xsnapshots, up_to_mode=max(SSMDim, show_modes))

In [15]:
# Plot variance description: we expect three modes to capture almost all variance.
# Note we assume data centered around the origin, which is the fixed point of our system.
plt.close('all')
plot.pca_modes(s**2, up_to_mode=show_modes)

### Project data onto dominant modes

In [16]:
Data['etaDataTrunc'] = deepcopy(Data['oDataTrunc'])
if observables == "delay-embedding":
    Vde = v[:, :SSMDim]
    for i in range(nTRAJ):
        Data['etaDataTrunc'][i][1] = Vde.T @ Data[svd_data][i][1]
elif observables == "pos-vel":
    assert SSMDim % 2 == 0
    Vde = np.kron(np.eye(2), v[:, :SSMDim//2])
    for i in range(nTRAJ):
        Data['etaDataTrunc'][i][1] = Vde.T @ np.vstack((Data[svd_data][i][1], np.gradient(Data[svd_data][i][1], DT, axis=1)))

In [17]:
plt.close('all')
# plot first three reduced coordinates
plot.traj_xyz(Data,
              xyz_idx=[('etaDataTrunc', 0), ('etaDataTrunc', 1), ('etaDataTrunc', 2)],
              xyz_names=[r'$x_1$', r'$x_2$', r'$x_3$'])

### Train and test data (train/test split)

In [18]:
indTest = [0, 8, 16, 24]
indTrain = [i for i in range(nTRAJ) if i not in indTest]

## SSMLearn

Start Matlab engine and install/run SSMLearn

In [19]:
ssm = utils.start_matlab_ssmlearn("/home/jonas/Projects/stanford/SSMR-for-control")

SSMLearn: Data-driven Reduced Order Models for Nonlinear Dynamical Systems
Maintained by Mattia Cenedese (mattiac@ethz.ch) and Joar Axs (jgoeransson@ethz.ch)
License: GNUv3.0
> In path (line 109)
In addpath (line 86)
In install (line 20)


Bring data in a format that is accepted by the (slightly modified) version of SSMLearn (requires a specific cell array structure for input data)

In [20]:
yDataTruncTrain_matlab = utils.numpy_to_matlab([Data['yDataTrunc'][i] for i in indTrain])
etaDataTruncTrain_matlab = utils.numpy_to_matlab([Data['etaDataTrunc'][i] for i in indTrain])

### Learn geometry of the SSM

Find parametrization of SSM using SSMLearn

In [21]:
IMInfo = ssm.IMGeometry(yDataTruncTrain_matlab, SSMDim, SSMOrder,
                        'reducedCoordinates', etaDataTruncTrain_matlab, 'l_vals', 0.)
if observables == "pos-vel":
    IMInfoInv = ssm.IMGeometry(etaDataTruncTrain_matlab, obsDim, SSMOrder,
                            'reducedCoordinates', yDataTruncTrain_matlab)
    for key in ['map', 'polynomialOrder', 'dimension', 'nonlinearCoefficients', 'phi', 'exponents', 'H']:
        IMInfo['chart'][key] = IMInfoInv['parametrization'][key]

Data seems to have been fed from Python!


### Learn dynamics on the SSM (reduced dynamics)

Find parametrization of reduced dynamics using SSMLearn

In [22]:
RDInfo = ssm.IMDynamicsFlow(etaDataTruncTrain_matlab, 'R_PolyOrd', ROMOrder, 'style', 'default', 'l_vals', 0.)

Data seems to have been fed from Python!
Estimation of the reduced dynamics... 
 Done. 


Stop Matlab engine -- not needed anymore

In [23]:
ssm.quit()

Convert all matlab double arrays to numpy arrays

In [24]:
utils.matlab_info_dict_to_numpy(IMInfo)
utils.matlab_info_dict_to_numpy(RDInfo)

Stability analysis of reduced dynamics

In [25]:
# assert np.all(np.real(RDInfo['eigenvaluesLinPartFlow']) < 0)
RDInfo['eigenvaluesLinPartFlow']

array([[ -2.16010864+10.84934519j],
       [ -1.79701649+10.89135767j],
       [-24.85707708 +0.j        ],
       [-10.18186198 +0.j        ],
       [ -2.16010864-10.84934519j],
       [ -1.79701649-10.89135767j]])

## Analyze the obtained mappings of SSM geometry and reduced dynamics

### SSM geometry (parametrization)

In [26]:
trajRec = {}
# geometry error
meanErrorGeo = {}
trajRec['geo'] = utils.lift_trajectories(IMInfo, Data['etaDataTrunc'])
normedTrajDist = utils.compute_trajectory_errors(trajRec['geo'], Data['yDataTrunc'])[0] * 100
meanErrorGeo['Train'] = np.mean(normedTrajDist[indTrain])
meanErrorGeo['Test'] = np.mean(normedTrajDist[indTest])
print(f"Average parametrization train error: {meanErrorGeo['Train']:.4e}")
print(f"Average parametrization test error: {meanErrorGeo['Test']:.4e}")

Average parametrization train error: 1.2984e-02
Average parametrization test error: 1.5373e-02


In [27]:
# plot comparison of SSM-predicted vs. actual test trajectories
plt.close('all')
axs = plot.traj_xyz(Data,
                    xyz_idx=[('yData', 0), ('yData', 1), ('yData', 2)],
                    xyz_names=[r'$x$ [mm]', r'$y$ [mm]', r'$z$ [mm]'],
                    traj_idx=indTest,
                    show=False)
plot.traj_xyz(trajRec,
            xyz_idx=[('geo', 0), ('geo', 1), ('geo', 2)],
            xyz_names=[r'$x$ [mm]', r'$y$ [mm]', r'$z$ [mm]'],
            traj_idx=indTest,
            axs=axs, ls=':', color='darkblue')

### Reduced dynamics

In [28]:
# reduced dynamics error
meanErrorDyn = {}
trajRec['rd'] = utils.advectRD(RDInfo, Data['etaDataTrunc'])[0]
normedTrajDist = utils.compute_trajectory_errors(trajRec['rd'], Data['etaDataTrunc'])[0] * 100
meanErrorDyn['Train'] = np.mean(normedTrajDist[indTrain])
meanErrorDyn['Test'] = np.mean(normedTrajDist[indTest])
print(f"Average dynamics train error: {meanErrorDyn['Train']:.4f}")
print(f"Average dynamics test error: {meanErrorDyn['Test']:.4f}")

/home/jonas/miniconda3/envs/soft/lib/python3.8/site-packages/sklearn/preprocessing/_polynomial.py:440: RuntimeWarning: overflow encountered in multiply
  np.multiply(
/home/jonas/Projects/stanford/SSMR-for-control/ROM/python/utils.py:96: RuntimeWarning: invalid value encountered in matmul
  N = lambda t, y: W_r @ phi(np.atleast_2d(y))


Average dynamics train error: inf
Average dynamics test error: inf


In [29]:
axs = plot.traj_xyz(Data,
                    xyz_idx=[('etaDataTrunc', 0), ('etaDataTrunc', 1), ('etaDataTrunc', 2)],
                    xyz_names=[r'$x_1$', r'$x_2$', r'$x_3$'],
                    traj_idx=indTest,
                    show=False)
plot.traj_xyz(trajRec,
            xyz_idx=[('rd', 0), ('rd', 1), ('rd', 2)],
            xyz_names=[r'$x_1$', r'$x_2$', r'$x_3$'],
            traj_idx=indTest,
            axs=axs, ls=':', color='darkblue')

### Global error

In [30]:
# global error
meanErrorGlo = {}
trajRec['glob'] = utils.lift_trajectories(IMInfo, trajRec['rd'])
normedTrajDist = utils.compute_trajectory_errors(trajRec['glob'], Data['yDataTrunc'])[0] * 100
meanErrorGlo['Train'] = np.mean(normedTrajDist[indTrain])
meanErrorGlo['Test'] = np.mean(normedTrajDist[indTest])
print(f"Average global train error: {meanErrorGlo['Train']:.4f}")
print(f"Average global test error: {meanErrorGlo['Test']:.4f}")

Average global train error: inf
Average global test error: inf


In [31]:
axs = plot.traj_xyz(Data,
                    xyz_idx=[('yData', 0), ('yData', 1), ('yData', 2)],
                    xyz_names=[r'$x$', r'$y$', r'$z$'],
                    traj_idx=indTest,
                    show=False)
plot.traj_xyz(trajRec,
            xyz_idx=[('glob', 0), ('glob', 1), ('glob', 2)],
            xyz_names=[r'$x$', r'$y$', r'$z$'],
            traj_idx=indTest,
            axs=axs, ls=':', color='darkblue')

## Understand which mode is responsible for what motion

In [32]:
if observables == "pos-vel":
    modesDir, modesFreq = utils.dominant_displacement_modes(RDInfo, Vde, SSMDim=SSMDim, tip_node=TIP_NODE, n_nodes=N_NODES)
    plot.mode_direction(modesDir, modesFreq)

## Control

### Setup model for control

In [33]:
Rauton = lambda x: RDInfo['reducedDynamics']['coefficients'] @ utils.multivariate_polynomial(x, RDInfo['reducedDynamics']['polynomialOrder'])
Vauton = lambda x: IMInfo['parametrization']['H'] @ utils.multivariate_polynomial(x, IMInfo['parametrization']['polynomialOrder'])
if observables == "pos-vel":
    Wauton = lambda y: IMInfo['chart']['H'] @ utils.multivariate_polynomial(y, IMInfo['chart']['polynomialOrder'])
elif observables == "delay-embedding":
    Wauton = lambda y: Vde.T @ y

### Learn control matrix $B$

Use randomly sampled inputs as the training and test data

In [34]:
inputData_dir = join(data_dir, "open-loop")
(t, z), u = utils.import_pos_data(inputData_dir, rest_file, TIP_NODE, return_inputs=True)
z = (z.T - q_eq).T
u = (u.T - u_eq).T
print(q_eq)

[ 0.54467017 35.57246381 -6.34727727]


Compute observables and reduced coordinates

In [35]:
y = assemble_observables(z_shift)
x = Wauton(y)

Train/test split

In [36]:
train_ratio = 0.8
split_idx = int(train_ratio * len(t))
t_train, t_test = t[:split_idx], t[split_idx:]
z_train, z_test = z[:, :split_idx], z[:, split_idx:]
y_train, y_test = y[:, :split_idx], y[:, split_idx:]
u_train, u_test = u[:, :split_idx], u[:, split_idx:]
x_train, x_test = x[:, :split_idx], x[:, split_idx:]

Plot the training data

In [37]:
plt.close('all')
plot.traj_xyz_txyz(t=t_train,
                   x=z_train[0, :], y=z_train[1, :], z=z_train[2, :])
plot.inputs(t_train, u_train)

Plot the test data

In [38]:
plt.close('all')
plot.traj_xyz_txyz(t=t_test,
                   x=z_test[0, :], y=z_test[1, :], z=z_test[2, :])
plot.inputs(t_test, u_test)

Compute gradient as predicted by reduced dynamics as well as the numerical (true) gradient

In [39]:
dxdt = np.gradient(x_train, DT, axis=1)
dxdt_ROM = Rauton(x_train)

Plot gradients (numerical differentiation and reduced dynamics)

In [40]:
plot.reduced_coordinates_gradient(t_train, [dxdt, dxdt_ROM], labels=["true numerical", "predicted autonomous"], how="all")

In [41]:
# plt.close('all')
# plot.dependence_of_xdot_on_inputs(dxDt, u_train_trunc)

Learn $B$ matrix

In [42]:
from sklearn.linear_model import Ridge

polyUorder = 1
# assemble_features = lambda u, x: utils.multivariate_polynomial(np.vstack([u, x]), order=polyUorder)
assemble_features = lambda u, x: utils.multivariate_polynomial(u, order=polyUorder)

X = assemble_features(u_train, x_train)

B_learn = utils.regress_B(X, dxdt, dxdt_ROM, alpha=0, method='ridge')
print(f"Frobenius norm of B_learn: {np.linalg.norm(B_learn, ord='fro'):.4f}")

Frobenius norm of B_learn: 0.9500


Plot gradients again, but this time, using the learned influence of inputs for the prediction

In [43]:
plt.close('all')
plot_reduced_coords = np.s_[:] # [3, 4, 5]
dxDt_ROM_with_B = Rauton(x_train) + B_learn @ assemble_features(u_train, x_train)
plot.reduced_coordinates_gradient(t_train, [dxdt[plot_reduced_coords, :], dxdt_ROM[plot_reduced_coords, :], dxDt_ROM_with_B[plot_reduced_coords, :]], labels=["true numerical", "predicted autonomous", "predicted with inputs"], how="all")

In [44]:
# # home-brewed ridge regression
# alpha = 0
# X, y = U.T, (dXbarDt - dXbarDt_ROM).T
# B_learn = np.linalg.solve(X.T @ X + alpha * np.eye(X.shape[0]), X.T @ y)

### Integrate model with inputs using learned influence of control (open-loop prediction)

Try to predict the different test trajectories using _non-autonomous_ reduced dynamics

In [45]:
R = lambda x, u: Rauton(np.atleast_2d(x)) + B_learn @ assemble_features(u, x)

Import test trajectory data

In [46]:
test_results = {}
test_trajectory_folders = ['open-loop_circle']
test_trajectories = [{
        'name': "like training data",
        't': t_test,
        'z': z_test,
        'u': u_test,
        'x': x_test
    }]
for test_traj in test_trajectory_folders:
    traj_dir = join(robot_dir, "dataCollection", test_traj)
    (t, z), u = utils.import_pos_data(data_dir=traj_dir,
                                      rest_file=rest_file,
                                      output_node=TIP_NODE, return_inputs=True, traj_index=0)
    z = (z.T - q_eq).T
    u = (u.T - u_eq).T
    y = assemble_observables(z)
    x = Wauton(y)
    test_trajectories.append({
            'name': test_traj,
            't': t,
            'z': z,
            'u': u,
            'x': x
        })

Do open loop prediction for all test trajectories; plot and save results

In [47]:
for traj in test_trajectories:
    z_pred = utils.predict_open_loop(R, Vauton, traj['t'], traj['u'], x0=traj['x'][:, 0])
    rmse = float(np.sum(np.sqrt(np.mean((z_pred[:3, :] - traj['z'][:3])**2, axis=0))) / len(traj['t']))
    print(f"({traj['name']}): RMSE = {rmse:.4f}")
    test_results[traj['name']] = {
        'RMSE': rmse
    }
    axs = plot.traj_xyz_txyz(traj['t'],
                                z_pred[0, :], z_pred[1, :], z_pred[2, :],
                                show=False)
    axs = plot.traj_xyz_txyz(traj['t'],
                                traj['z'][0, :], traj['z'][1, :], traj['z'][2, :],
                                color="tab:orange", axs=axs, show=False)
    axs[-1].legend(["Predicted trajectory", "Actual trajectory"])
    plt.show()
print(f"(overall): RMSE = {np.mean([test_results[traj]['RMSE'] for traj in test_results]):.4f}")

(like training data): RMSE = 0.3953
(open-loop_circle): RMSE = 7.4780
(overall): RMSE = 3.9366


## Save SSM model

In [48]:
settings = {
    'SSMDim': SSMDim,
    'SSMOrder': SSMOrder,
    'ROMOrder': ROMOrder,
    'observables': observables,
    'poly_u_order': polyUorder,
    'oDOF': oDOF,
    'input_dim': INPUT_DIM,
    'n_delay': N_DELAY
}
utils.save_ssm_model(join(robot_dir, "SSMmodels"), RDInfo, IMInfo, B_learn, Vde, settings, test_results)